#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#include "cell.h"

/**
 * Fluid viscosity. It slows down the cell's movement in the fluid.
 */
#define LAMBDA 0.00001

/**
 * Mass of the cell. Depending on it, the cell gains more or less velocity.
 */
#define MASS 0.1

/**
 * Size of each misuration timestep
 */
#define TIMESTEP 1

#define PI 3.14159265358979323846

/**
 * Two random numbers following a normal distribution generated by Box-Muller method.
 */
float box_muller_number[2];

/**
 * Using Langevin equation and following a brownian motion inside a fluid, it updates cell coordinates.
 * @param cell cell to update its current velocity and position
 */
void update_cell_Langevin(Cell* cell);

/**
 * It generates two random numbers following a normal distribution.
 */
void box_muller();

int main(int argc, char const *argv[])
{
    srand(time(NULL));
    Cell cell = {
        .velocity = {
            .x = 0.1,
            .y = 0.1
        },
        .position = {
            .x = 100,
            .y = 100
        }
    };
    for (int i = 0; i < 100; i++) {
        update_cell_Langevin(&cell);
        printf("x: %f \t y: %f \n", cell.position.x, cell.position.y);
    }
    return 0;
}

void update_cell_Langevin(Cell* cell) 
{
    box_muller();
    Vector delta_velocity = {
        .x = (-LAMBDA * cell->velocity.x + box_muller_number[0]) / MASS * TIMESTEP,
        .y = (-LAMBDA * cell->velocity.y + box_muller_number[1]) / MASS * TIMESTEP
    };
    cell->velocity.x += delta_velocity.x;
    cell->velocity.y += delta_velocity.y;
    cell->position.x += cell->velocity.x * TIMESTEP;
    cell->position.y += cell->velocity.y * TIMESTEP;
}

void box_muller()
{
    float 
        u1 = (float)rand()/(float)(RAND_MAX),
        u2 = (float)rand()/(float)(RAND_MAX);
    box_muller_number[0] = sqrt(-2 * log(u1)) * cos(2 * PI * u2);
    box_muller_number[1] = sqrt(-2 * log(u1)) * sin(2 * PI * u2);
}
