all:
	gcc langevin.c -o exe/langevin -lm

run:
	./exe/langevin

discrete:
	gcc discrete_langevin.c -o exe/discrete_langevin -lm

run-discrete:
	./exe/discrete_langevin

clear:
	-rm ./exe/*